# This workflow checks out code, builds an image, generates SARIF format vuln report for Github ACS
# (optionally breaking the build at this point if there are vulns above a given severity), pushes the
# image to a registry, and adds it to the Anchore Enterprise queue

name: Anchore Weekly

on: 
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: '52 23 * * 5'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Manual Build'  
        
env:
  ANCHORE_CLI_USER: ${{ secrets.ANCHORE_CLI_USER }}
  ANCHORE_CLI_PASS: ${{ secrets.ANCHORE_CLI_PASS }}
  ANCHORE_CLI_URL: ${{ secrets.ANCHORE_CLI_URL }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_TAG: weekly
  
  
jobs:

  Build-Push:
    runs-on: ubuntu-latest
    steps:

    - name: "Set environmental variables"
      run: |
        echo "IMAGE=${IMAGE_REGISTRY}/${GITHUB_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v2      

    - name: Build Image
      run: |
        docker build . --file Dockerfile --tag ${IMAGE}
        
    ### use the grype scan action to hydrate the Code Scanning Alerts in the Security tab
    ### you could choose to break the build here before pushing based on results
    - name: Scan Image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: ${{ env.IMAGE }}
        fail-build: false
        severity-cutoff: critical
        acs-report-enable: true        
    - name: Upload Anchore Scan SARIF Report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    - name: Login to Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${IMAGE_REGISTRY} -u ${GITHUB_ACTOR} --password-stdin

    - name: Push Docker Image
      run: |
        docker push ${IMAGE}



  Enterprise-Scan:
    needs: Build-Push
    runs-on: ubuntu-latest
    
    steps:
    
    - name: "Set environmental variables"
      run: |
        echo "IMAGE=${IMAGE_REGISTRY}/${GITHUB_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_ENV

    - name: Checkout Code
      uses: actions/checkout@v2      
            
    - name: Install anchore-cli
      run: |
        sudo apt-get install python3-pip
        pip install anchorecli
        export PATH="$HOME/.local/bin/:$PATH"
        
    - name: Verify Anchore Ready and Reachable
      run: |
        anchore-cli system status 
        
    - name: Add to Enterprise Queue
      run: | 
        anchore-cli image add --noautosubscribe --force --dockerfile ./Dockerfile --annotation build_tool=github --annotation actor=${GITHUB_ACTOR} ${IMAGE}
        
    ### don't really need to wait if you're not going to activate subs afterwards
    #
    #- name: Wait for Enterprise Analysis
    #  run: |
    #    anchore-cli image wait ${IMAGE}
    #   
    ### uncomment these if you want to activate policy/vuln updates
    #
    #- name: Activate Policy and Vulnerability Subscriptions
    #  run: |
    #    anchore-cli subscription activate policy_eval ${IMAGE}
    #    anchore-cli subscription activate vuln_update ${IMAGE}
